version: '3'

services:
  postgres_db:
    image: postgres:9.6-alpine
    ports:
    - "15432:5432"
    environment:
    - POSTGRES_USER=bookstore
    - POSTGRES_PASSWORD=bookstore
    - POSTGRES_DB=bookstore
  web_app:
    build: ./
    volumes:
    - ./data/web:/app/data
    - ./local.docker.py:/app/config/local_settings.py
    ports:
    - "8007:80"
