# Generated by Django 2.1.1 on 2018-09-17 07:09

from decimal import Decimal
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, unique=True, verbose_name='full name')),
                ('info', models.TextField(blank=True, null=True, verbose_name='information')),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='title')),
                ('isbn', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'Length has to be 10 and only digits are allowed.', 'nomatch')], verbose_name='International Standard Book Number')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Only positive number are allowed.')], verbose_name='price')),
                ('publish_date', models.DateField(null=True, verbose_name='publish date')),
                ('authors', models.ManyToManyField(to='core.Author')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
                'db_table': 'book',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='WebRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='request')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='request')),
            ],
            options={
                'verbose_name': 'web request',
                'verbose_name_plural': 'web requests',
                'db_table': 'web_request',
                'ordering': ('-date',),
            },
        ),
    ]
